In [1]:
import numpy as np
from numpy import linalg as LA
als = [[1,1,1,0,0],[-3,-3,-3,0,0],[2,2,2,0,0],[0,0,0,-1,-1],[0,0,0,2,2],[0,0,0,-1,-1]]
a = np.array(als)
at = a.transpose()
print(a)
print(at)

[[ 1  1  1  0  0]
 [-3 -3 -3  0  0]
 [ 2  2  2  0  0]
 [ 0  0  0 -1 -1]
 [ 0  0  0  2  2]
 [ 0  0  0 -1 -1]]
[[ 1 -3  2  0  0  0]
 [ 1 -3  2  0  0  0]
 [ 1 -3  2  0  0  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0 -1  2 -1]]


In [2]:
LA.eig(at.dot(a))

(array([ 4.20000000e+01,  3.25270202e-15, -5.39911721e-32,  1.20000000e+01,
        -1.77635684e-15]),
 array([[ 5.77350269e-01, -7.14981744e-01, -9.72189245e-17,
          0.00000000e+00,  0.00000000e+00],
        [ 5.77350269e-01,  6.98959508e-01, -7.07106781e-01,
          0.00000000e+00,  0.00000000e+00],
        [ 5.77350269e-01,  1.60222362e-02,  7.07106781e-01,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          7.07106781e-01, -7.07106781e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          7.07106781e-01,  7.07106781e-01]]))

In [3]:
np.set_printoptions(suppress=True)
np.linalg.svd(a)

(array([[-0.26726124,  0.        , -0.94816592,  0.        , -0.17190932,
          0.        ],
        [ 0.80178373,  0.        , -0.31776533,  0.        ,  0.50613047,
          0.        ],
        [-0.53452248,  0.        , -0.00256504,  0.        ,  0.84515036,
          0.        ],
        [ 0.        , -0.40824829,  0.        , -0.91287093,  0.        ,
         -0.        ],
        [ 0.        ,  0.81649658,  0.        , -0.36514837,  0.        ,
          0.4472136 ],
        [ 0.        , -0.40824829,  0.        ,  0.18257419,  0.        ,
          0.89442719]]),
 array([6.4807407 , 3.46410162, 0.        , 0.        , 0.        ]),
 array([[-0.57735027, -0.57735027, -0.57735027,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.70710678],
        [ 0.81649658, -0.40824829, -0.40824829,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -0.70710678,  0.70710678],
        [ 0.        , -0.70710678,  0.70710678

In [11]:
from scipy.linalg import svd
from numpy import zeros
from numpy import diag
U, s, VT = svd(a)
# create m x n Sigma matrix
Sigma = zeros((a.shape[0], a.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:a.shape[1], :a.shape[1]] = diag(s)
print(U, "\n", Sigma, "\n", VT)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))

[[-0.26726124  0.         -0.94816592  0.         -0.17190932  0.        ]
 [ 0.80178373  0.         -0.31776533  0.          0.50613047  0.        ]
 [-0.53452248  0.         -0.00256504  0.          0.84515036  0.        ]
 [ 0.         -0.40824829  0.         -0.91287093  0.         -0.        ]
 [ 0.          0.81649658  0.         -0.36514837  0.          0.4472136 ]
 [ 0.         -0.40824829  0.          0.18257419  0.          0.89442719]] 
 [[6.4807407  0.         0.         0.         0.        ]
 [0.         3.46410162 0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]] 
 [[-0.57735027 -0.57735027 -0.57735027  0.          0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829 -0.40824829  0.          0.        ]
 [ 0.  